language: generic
sudo: required
services:
- docker
env:
  global:
    - secure: "T9X2KGHVt81pUTF5exIv+SUNEz2lHqdkCpm1Pf/Wut6C3Vp1ANc5G8JLNGUwgDZpXsu5ENDLdHm5O5OojTFcrPRXIvRYJBf+Wr53Yj8W3jwgUlVCYDgIRAN8T7wSaJjGb3DzJ2EP/+A6wro8d+MO6I9kdki+IM1cTJWhLTyvHzg/SAurjtQwMAOsNXKbYn7NhHyPeEns3TMKtyaj+CE3SBr1tpUqPtGa79SYYa/RRVV0StpmiPEvdDVvKrg+YK5W5s4gofPTDDvAc9dTCAb+X5I43pfMELl/vSbB3DIiKYAJO0HgOHg/x+ea5GBemjm8OX189fpkz9A0AI7SIbDFqdpI0z3l2zXfNKSuLMEd+p5deNg6zkr2nnROAE31Mtrvx+ehZuPXGC7GScnhoa/YgGNctnJUyfqOZI6MG0YnPBJsGjlmvlQEUl1dQ1l6hZ721Stk0j6EWZVOkgFoMIo+6WqeWGsKEhZd9OSb06sxEXEyL/6EiclRhR9KMybGSxEb0Ph5Fu16JdNcOgRWRes+T8d4fBT3vwFD+Mdvp+AxNZLPlH9K4CE5F7CbJg54xjeSSOmlP2tI0ibrxGqrq2nEEkw6m4u6KzhybqfOgWlbtc6lEoXNkFl6EI/s9gc1DS9f7Ql8pb8p2atlPRp4KiGgNskDLnYqk3e82BO5yMfVy/A="
    - secure: "zS4yJI+ecQ4224xT+TT1thRtaWI7ltYHbnH9cS65HXBmvxJoCiyo/zPCQBK1tP0H7ElArebSnYY5GZ/CVNdtsju53WvpxABoUmvHQHBmT+s5V3DiXzJUUnHxM7YvKU9q5aoC6xHSwI+SZ1ZcRxImwXb3mIqMOQpB78kArz8pCUIhrCOYlTuBcnv2go/0GotueY6lLHUwfTbNsKFoDeXvAaFzSdUEb3NRl0996JCCigy5RHm34VIOKuSDmg1JUnorrem9OBbIsBAUi9PvyMcaJxD4sjiTE+cb69efCFHSRQCv255xN/7fMlTqAUHBhOmREWLy2B2pW40P6cJ8HLgUTv//EvGpM+ErI5G76O++FsGXMQOGea1+pt2/icSemq1PLDbqaI9MqtD84YYyVW95dLlBnulab3UJ6n+FjmdFrG16QwPYAfIv6TwldMPw0/N3LsQqoohzZTkuKrpZ+wNns1ZOQJaHixp4xUc3f9Tt1mrfjvIKOhY2TPlcVBwBJotQ4Ps5iMYXsEmJb7dwSSmTDYMbXoH4cDDAqL8804tHLLPAilQ2Ea0m5s9OvGd9qdHgRwBA1YP6s02lTAsWPy7eNMxxmpNBTyab4zKB/b5kVpuDHVak2QngdF06V2SMXeBwmIUbsE2oiKmw4NRGY3JodzqzogwbxuPhxI5vKUhYrK4="
deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      tags: true
      branch: master
