language: generic
sudo: required
services:
- docker
env:
  global:
    - secure: "jN+j8mrHhjBmEFWZ3WSyHB28WXlRs8XMusf1xj1tKGSOGoHDWgGCsK/ffm7hUK/vWMmlA2XzRSaDSax2voFCOQqFbumr3DehEZgS2QU54/KFvIm5sOsHPrVPn/HQ1kbqmhjN1JHjjRkoaOE7+I43mHk1pyPY542pEL++HTMDttRcIbgVe5kA5nzMREdmpRZEveFuQ2nhTEVG46ofqeJYj3Pi3Yg6UPVUXjuGe++Q906JXKbTvgt86iBLnMPvpLNfBGopp5H03MplqoXi+IJB5QUZuXNz/NNHVZV/zBhUmRcJbXtA51MQkNkKSoOMTdaHNRX7eg8fo2kp+2AT5FO06lyeMTdxjhX1fMZC6SzNSj5BKMJS+4SUUO3fQ3I5X45etSmLzDI0U2hf4xFi8RWTCXvaaoapeAXb63aekLeezwHZrLGx3kod40hD2ST3h8+tswuP0Rws4ptI0daOT3NWPH9nHhGCkYWHK5RgLpWwAA5bjqlCG2VqU24NmbNCESyXqLa1GJkY+GPflQ4JY6S0oPzxjuhidkHDtnD8vD4O2OrgyQRY/LO8yXh6b/tUgksd2o/Aismbh7Q3Bwdi04iPwcWF7eydVokHuLKy9SbGaM0LcTEY7D9pyY4tWFEKoK7MpE+z/Wok+qUOYd3Nag1frFDawVjM9SaqDychEtMxqd0="
    - secure: "PzBhLjrnKWpnQZbL/8TebfZJ1u/BighIjQgD9CaLYXO9YU6ia08/EHjkELS2SV2bGKbrjIEfz5c4mhFEBtuLWb+ZHk6pYc2K2MTVF8imXxCZjaF+L+ULWR5ujNzYIuYIOM/aEcz+aPa9+wCvGDKQKMZBZnoBqtpwCarPY36j+e0ZWSRuH8gH2vFKMOCRYAOcCZ4FfJqdLa/duH6TibseEVsbB7W1iKDfIX8CVNdgiTJ00YParjWfr3McXKPnXQ7hwS8836oiBdqiJ97c35vusNGRrgdoQdTlWw5a2N7w1Knw4g9NqWV++TAcF5wywZmhOrQyO2BZPUT97XJip+THuYHmFW9US0JAXoqwul1vkLqn6VBLeKR3i+huC70ao1v2/cl4+7vNQ/FzpEPfZIKrlrjTeUwRuIoLMnqQ4yjTMBHEu1Dnl6FkZIO8mbbeNzuD/MF57SsX81GKgHuFdSTlISR428enZBTxsv/XzbcYt2ISkd/vxvrXYC3WxAx4pFajNQwGVKs3TY5REheqr180khaj5u/xSKBfoJxBomk7oRuyyw1+AFlwkfD1BQyIDJGdKSKlzIyoET65QoZOopgWcHzl+grwUy2Q8ojtU2BC0+pDhT1qqDEhoDdbFHHpYgzzskHcjc9jeau9/WuasbBdz0jHQSaSyT4mF/Mv1iEsVDE="
deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      tags: true
      branch: master
