FROM debian:stretch

COPY --from=napalmautomation/napalm:2.4.0 /usr/lib/python2.7/dist-packages/ /usr/lib/python2.7/dist-packages/
COPY --from=napalmautomation/napalm:2.4.0 /usr/local/lib/python2.7/dist-packages/ /usr/local/lib/python2.7/dist-packages/

MAINTAINER ping@mirceaulinic.net

ARG version=""

RUN apt-get update \
 && apt-get install -y python-pip \
 && apt-get autoremove \
 && rm -rf /var/lib/apt/lists/* \
 && pip --no-cache-dir install salt==$version

## Copy the Proxy config file
ADD proxy /etc/salt/proxy

# Add Run File
ADD run-proxy.sh /usr/local/bin/run-proxy.sh

# Run Command
CMD "/usr/local/bin/run-proxy.sh"
