FROM debian:stretch

MAINTAINER ping@mirceaulinic.net

ARG version=""

RUN apt-get update \
 && apt-get install -y python-pip \
 && apt-get autoremove \
 && rm -rf /var/lib/apt/lists/* \
 && pip --no-cache-dir install salt==$version

ADD master /etc/salt/master

# Add Run File
ADD run-master.sh /usr/local/bin/run.sh

# Ports
EXPOSE 4505 4506

# Run Command
CMD "/usr/local/bin/run.sh"
